name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v1
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - shell: bash
      run: bun add -g turbo

    - shell: bash
      run: bun install
